version: '0.0.1'

services:
  app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: user
        DB_PASSWORD: password
        DB_NAME: new_storage_db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: new_storage_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: